/* <unistd.h> for Visual C++, which has none -- added to the include path of
   GAOL's build by scripts/CMakeModules/gaol/gaol/CMakeLists.txt of Codac.

   The lexer of GAOL, generated by flex (gaol/gaol_interval_lexer.cpp), includes
   <unistd.h> and calls isatty(), which Visual C++ declares in <io.h>. The fork
   of GAOL by Fabrice Le Bars (https://github.com/lebarsfa/GAOL) gives Visual
   C++ a fuller <unistd.h> for the same reason (3rd/unistd.h, from
   https://github.com/ENSTABretagneRobotics/OSUtils); isatty() is all the lexer
   needs. */

#ifndef CODAC_GAOL_MSVC_UNISTD_H
#define CODAC_GAOL_MSVC_UNISTD_H

#include <io.h>

#endif /* CODAC_GAOL_MSVC_UNISTD_H */
